BOARD_URL = "https://glowfic.com/board_sections/703"

VOICE_DICT = {
    "Lady Eul\u00e0lia Avaricia de Seguer": "TBD",
    "Minor Character": "TBD",
    "Character 1": "TBD",
    "Class Chatter": "TBD",
    "Tira Shabbar": "TBD",
    "Ri-Dul": "TBD",
    "Ostenso": "TBD",
    "Aspexia Rugatonn": "TBD",
    "Ferrer Maillol": "TBD",
    "Mayor of Senara": "TBD",
    "Merenre": "TBD",
    "Abadar": "TBD",
    "Greater Iomedae": "TBD",
    "Erecura": "TBD",
    "Abrogail Thrune II": "TBD",
    "Zon-Kuthon": "TBD",
    "Halfling slave #958245 \"Broom\"": "TBD",
    "???": "TBD",
    "Pilar ": "TBD",
    "Tarnish": "TBD",
    "Nefreti Clepati": "TBD",
    "Character 2": "TBD",
    "Ione Sala": "TBD",
    "Irori": "TBD",
    "Alexandre Esquerra": "TBD",
    "Zakiya": "TBD",
    "Athpechya": "TBD",
    "Greater Reality": "TBD",
    "Pit Fiend": "TBD",
    "Carissa's imaginary Keltham": "TBD",
    "Peranza of Civilization": "TBD",
    "Jacint Subirachs": "TBD",
    "Keltham v3": "TBD",
    "Abrogail": "TBD",
    "Chelish Noble": "TBD",
    "Carissa Sevar": "TBD",
    "Roc de Castell": "TBD",
    "Keltham": "TBD",
    "Keltham v4": "TBD",
    "dath ilani": "TBD",
    "Other Women Have Wanted To Strangle Boyfriends But Never With This Much Justification Quantitatively Speaking": "TBD",
    "Rosal Monserrat": "TBD",
    "Keltham?": "TBD",
    "Ruby Prince Khemet III": "TBD",
    "Befutig Safiza Uj-alet": "TBD",
    "Modavian": "TBD",
    "Peranza": "TBD",
    "Milani": "TBD",
    "Cayden Cailean": "TBD",
    "Cheliax": "TBD",
    "literal fucking IOUN stone": "TBD",
    "Absalom": "TBD",
    "Ismat Alnahhat": "TBD",
    "Derrina": "TBD",
    "Tiny Translucent Sphere": "TBD",
    "Incredibly Terrified Prisoner": "TBD",
    "AlterPeranza": "TBD",
    "Asmodeus": "TBD",
    "Pilar Pineda": "TBD",
    "Isfahel, Kelesh": "TBD",
    "Curse of Laughter": "TBD",
    "Prince Fe-Anar": "TBD",
    "Mora of Maragall": "TBD",
    "Akkakarasot": "TBD",
    "Hadrian": "TBD",
    "A Somewhat Dubious Model of Keltham": "TBD",
    "Classroom": "TBD",
    "Willa Shilira": "TBD",
    "Alexite Gellius Rutilus Thrune": "TBD",
    "Oppara": "TBD",
    "Dispater": "TBD",
    "Hemaka": "TBD",
    "Olegario": "TBD",
    "Elysium": "TBD",
    "Nethys": "TBD",
    "Carissa's Model of Keltham": "TBD",
    "Gorthoklek": "TBD",
    "Iomedae": "TBD",
    "Korva Tallandria": "TBD",
    "Maillol's Remains": "TBD",
    "Phistophilus": "TBD",
    "Merrin": "TBD",
    "Indapatta": "TBD",
    "Security": "TBD",
    "Infernal Fortress": "TBD",
    "Shelyn": "TBD",
    "Calistria": "TBD",
    "dath Keltham??": "TBD",
    "Carmin Isandre": "TBD",
    "Asmodia": "TBD",
    "Greater Asmodia": "TBD",
    "Ex-Criminal Wizard Student Who Received His Wish To Have His Criminality Beaten Out Of Him": "TBD",
    "Keltham+": "TBD",
    "Anashala": "TBD",
    "Road": "TBD",
    "Carissa's Model of Aspexia": "TBD",
    "Sajvara": "TBD",
    "dath ilan": "TBD",
    "Terrified Newly-Assigned Assistant Enchanter Who Wasn't Briefed Very Much And Is Now Certain He's Going To Die Horribly": "TBD",
    "Otolmens": "TBD",
    "City of Brass": "TBD",
    "Glosialabolas": "TBD",
    "Thellim": "TBD",
    "Nanhsa": "TBD",
    "Project Lawful": "TBD",
    "AAAAAAAAAAA (Security)": "TBD",
    "Taravind": "TBD"
}