BOARD_URL = "https://glowfic.com/board_sections/703"

JSON_PATH = "data/threads JSON"

VOICE_DICT = {
    "Keltham": (keltham_voice:="Keltham"),
    "Keltham+": keltham_voice,
    "Keltham v3": keltham_voice,
    "dath Keltham??": keltham_voice,
    "Keltham v4": keltham_voice,
    "Keltham?": keltham_voice,
    "dath ilani": keltham_voice,
    "Carissa's imaginary Keltham": keltham_voice,
    "Carissa's Model of Keltham": keltham_voice,
    "A Somewhat Dubious Model of Keltham": keltham_voice,
    
    "Carissa Sevar": (carissa_voice:="Carissa"),

    "Narrator": (narrator_voice:="Narrator"),
    "Security": narrator_voice,
    "dath ilan": narrator_voice,
    "Cheliax": narrator_voice,
    "Project Lawful": narrator_voice,
    "Greater Reality": narrator_voice,
    "AAAAAAAAAAA (Security)": narrator_voice,
    "Classroom": narrator_voice,

    "Asmodia": (asmodia_voice:="Asmodia"),
    "Greater Asmodia": asmodia_voice,
    "Abrogail Thrune II": (abrogail_voice:="Abrogail"),
    "Abrogail": abrogail_voice,
    "Pilar ": (pilar_voice:="Pilar"),
    "Pilar Pineda": pilar_voice,
    "Ione Sala": (ione_voice:="Ione"),
    "Aspexia Rugatonn": (aspexia_voice:="Aspexia"),
    "Carissa's Model of Aspexia": aspexia_voice,
    "Jacint Subirachs": (jacint_voice:="Jacint"),
    "Korva Tallandria": (korva_voice:="Korva"),
    "Peranza": (perenza_voice:="Peranza"),
    "Peranza of Civilization": perenza_voice,
    "AlterPeranza": perenza_voice,
    "Derrina": (derrina_voice:="Derrina"),
    "Lady Eulàlia Avaricia de Seguer": (lady_avaricia_voice:="Lady Avaricia"),
    "Lady Eul\u00e0lia Avaricia de Seguer": lady_avaricia_voice,
    "Nefreti Clepati": (nefreti_voice:="Nefreti"),

    "Ferrer Maillol": (ferrer_voice:="Ferrer"),
    "Maillol's Remains": ferrer_voice,
    "Merenre": (merenre_voice:="Merenre"),
    "Prince Fe-Anar": (fe_anar_voice:="Fe-Anar"),
    "Ruby Prince Khemet III": (khemet_3_voice:="Khemet III"),
    "Halfling slave #958245 \"Broom\"": (broom_voice:="Broom"),
    "Ri-Dul": (ri_dul_voice:="Ri-Dul"),
    "Incredibly Terrified Prisoner": (terrified_prisoner_voice:="Terrified Prisoner"),
    "Befutig Safiza Uj-alet": (befutig_voice:="Befutig"),

    "Curse of Laughter": (curse_of_laughter_voice:="Curse of Laughter"),
    "Cayden Cailean": (cayden_cailean_voice:="Cayden Cailean"),
    "Dispater": (dispater_voice:="Dispater"),
    "Indapatta": (indapatta_voice:="Indapatta"),
    "Asmodeus": (asmodeus_voice:="Asmodeus"),
    "Irori": (irori_voice:="Irori"),
    "???": (question_mark_voice:="???"),
    "City of Brass": (city_of_brass_voice:="City of Brass"),
    "Abadar": (abadar_voice:="Abadar"),
    "Zakiya": (zakiya_voice:="Zakiya"),
    "Otolmens": (otolmens_voice:="Otolmens"),
    "Milani": (milani_voice:="Milani"),
    "Iomedae": (iomedae_voice:="Iomedae"),
    "Greater Iomedae": iomedae_voice,
    "Zon-Kuthon": (zon_kuthon_voice:="Zon-Kuthon"),
    "Nethys": (nethys_voice:="Nethys"),
    "Gorthoklek": (gorthoklek_voice:="Gorthoklek"),
    "Pit Fiend": (pit_fiend_voice:="Pit Fiend"),

    "Glosialabolas": (glosialabolas_voice:="Glosialabolas"),
    "Taravind": (taravind_voice:="Taravind"),
    "Hadrian": (hadrian_voice:="Hadrian"),
    "Absalom": (absalom_voice:="Absalom"),
    "Sajvara": (sajvara_voice:="Sajvara"),
    "Tarnish": (tarnish_voice:="Tarnish"),
    "Ostenso": (ostenso_voice:="Ostenso"),
    "Phistophilus": (phistophilus_voice:="Phistophilus"),
    "Ismat Alnahhat": (ismat_alnahhat_voice:="Ismat Alnahhat"),
    "Ex-Criminal Wizard Student Who Received His Wish To Have His Criminality Beaten Out Of Him": (ex_criminal_wizard_student_voice:="Ex-Criminal Wizard Student"),
    "Rosal Monserrat": (rosal_monserrat_voice:="Rosal Monserrat"),
    "Elysium": (elysium_voice:="Elysium"),
    "Hemaka": (hemaka_voice:="Hemaka"),
    "literal fucking IOUN stone": (ioun_stone_voice:="Ioun Stone"),
    "Class Chatter": (class_chatter_voice:="Class Chatter"),
    "Mayor of Senara": (mayor_of_senara_voice:="Mayor of Senara"),
    "Minor Character": (minor_character_voice:="Minor Character"),
    "Road": (road_voice:="Road"),
    "Infernal Fortress": (infernal_fortress_voice:="Infernal Fortress"),
    "Roc de Castell": (roc_de_castell_voice:="Roc de Castell"),
    "Olegario": (olegario_voice:="Olegario"),
    "Carmin Isandre": (carmin_isandre_voice:="Carmin Isandre"),
    "Calistria": (calistria_voice:="Calistria"),
    "Alexite Gellius Rutilus Thrune": (alexite_voice:="Alexite"),
    "Terrified Newly-Assigned Assistant Enchanter Who Wasn't Briefed Very Much And Is Now Certain He's Going To Die Horribly": (terrified_newly_assigned_assistant_enchanter_voice:="Terrified Newly-Assigned Assistant Enchanter"),
    "Alexandre Esquerra": (alexandre_esquerra_voice:="Alexandre Esquerra"),
    "Chelish Noble": (chelish_noble_voice:="Chelish Noble"),
    "Thellim": (thellim_voice:="Thellim"),
    "Shelyn": (shelyn_voice:="Shelyn"),
    "Isfahel, Kelesh": (isfahel_kelesh_voice:="Isfahel, Kelesh"),
    "Oppara": (oppara_voice:="Oppara"),
    "Tiny Translucent Sphere": (tiny_translucent_sphere_voice:="Tiny Translucent Sphere"),
    "Athpechya": (athpechya_voice:="Athpechya"),
    "Erecura": (erecura_voice:="Erecura"),
    "Other Women Have Wanted To Strangle Boyfriends But Never With This Much Justification Quantitatively Speaking": (other_women_voice:="Other Women"),
    "Mora of Maragall": (mora_of_maragall_voice:="Mora of Maragall"),
    "Anashala": (anashala_voice:="Anashala"),
    "Akkakarasot": (akkakarasot_voice:="Akkakarasot"),
    "Tira Shabbar": (tira_shabbar_voice:="Tira"),
    "Nanhsa": (nanhsa_voice:="Nanhsa"),
    "Modavian": (modavian_voice:="Modavian"),
    "Willa Shilira": (willa_voice:="Willa"),
    "Merrin": (merrin_voice:="Merrin"),
    "Character 1": (character_1_voice:="C1"),
    "Character 2": (character_2_voice:="C2")
}